[phases.setup]
nixPkgs = ['nodejs', 'ffmpeg']
aptPkgs = ['ffmpeg']

[phases.install]
cmds = ['npm ci']

[phases.build]
cmds = ['npm run build']

[phases.start]
cmd = 'chmod +x railway-start.sh && ./railway-start.sh'
